# Generated by Django 3.0.2 on 2020-06-16 05:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=256)),
                ('airport', models.CharField(default='NA', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, max_length=256)),
                ('orderid', models.CharField(default='NA', max_length=256, unique=True)),
                ('quantity', models.IntegerField(default=1, max_length=256)),
                ('accept', models.IntegerField(default=-1, max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 16, 5, 48, 30, 804175, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=256, unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('objectname', models.CharField(default='NA', max_length=256)),
                ('airport', models.CharField(default='NA', max_length=256)),
                ('category', models.CharField(default='NA', max_length=256)),
                ('services', models.CharField(default='NA', max_length=256)),
                ('doctor', models.BooleanField(default=False)),
                ('latitude', models.CharField(default='0.00', max_length=256, null=True)),
                ('longitude', models.CharField(default='0.00', max_length=256, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 16, 5, 48, 30, 802039, tzinfo=utc))),
                ('active', models.BooleanField(default=False)),
                ('risk', models.IntegerField(default=0, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=256)),
                ('amount', models.FloatField(max_length=10)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 16, 5, 48, 30, 807184, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='storerestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparing_packaging', models.BooleanField(default=False)),
                ('dispatched', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('Rating', models.FloatField(default=0.0, max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 16, 5, 48, 30, 805281, tzinfo=utc))),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(default='NA', max_length=256)),
                ('productid', models.CharField(default='NA', max_length=256, unique=True)),
                ('productDescription', models.CharField(default='NA', max_length=256)),
                ('stock', models.IntegerField(default=-1, max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('display', models.CharField(default='https://www.vikasanvesh.in/wp-content/themes/vaf/images/no-image-found-360x260.png', max_length=256, null=True)),
                ('costPrice', models.FloatField(default=0.0, max_length=256)),
                ('sellingPrice', models.FloatField(default=0.0, max_length=256)),
                ('discount', models.FloatField(default=0.0, max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.CharField(default='NA', max_length=256)),
                ('checkout', models.CharField(default='NA', max_length=256)),
                ('Rating', models.FloatField(default=0.0, max_length=256)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet', models.BooleanField(default=False)),
                ('chat', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 16, 5, 48, 30, 805864, tzinfo=utc))),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintxn', models.CharField(default='COMP123', max_length=256)),
                ('complain', models.CharField(max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 16, 5, 48, 30, 806569, tzinfo=utc))),
                ('complainid', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=0)),
                ('username', models.CharField(default='USER1', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
