# Generated by Django 3.0.2 on 2020-05-02 09:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='cab',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='store',
        ),
        migrations.AddField(
            model_name='order',
            name='accept',
            field=models.IntegerField(default=-1, max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.CharField(default='NA', max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 9, 54, 6, 210491, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='productid',
            field=models.CharField(default='NA', max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='category',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 9, 54, 6, 208624, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='storerestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparing_packaging', models.BooleanField(default=False)),
                ('dispatched', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('Rating', models.FloatField(default=0.0, max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 5, 2, 9, 54, 6, 211908, tzinfo=utc))),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.CharField(default='NA', max_length=256)),
                ('checkout', models.CharField(default='NA', max_length=256)),
                ('Rating', models.FloatField(default=0.0, max_length=256)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
    ]
