# Generated by Django 3.0.2 on 2020-05-30 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200502_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='services',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 7, 13, 51, 644159, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 7, 13, 51, 645240, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 7, 13, 51, 642240, tzinfo=utc)),
        ),
    ]
