# Generated by Django 3.0.2 on 2020-05-30 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200530_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 17, 9, 35, 458143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.CharField(default='https://www.vikasanvesh.in/wp-content/themes/vaf/images/no-image-found-360x260.png', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 17, 9, 35, 459921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 17, 9, 35, 455041, tzinfo=utc)),
        ),
    ]
