# Generated by Django 3.0.2 on 2020-06-08 10:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20200530_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='latitude',
            field=models.CharField(default='0.00', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='longitude',
            field=models.CharField(default='0.00', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='risk',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 10, 30, 55, 142488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 10, 30, 55, 143557, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 10, 30, 55, 139670, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet', models.BooleanField(default=False)),
                ('chat', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 8, 10, 30, 55, 144093, tzinfo=utc))),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
