# Generated by Django 3.0.2 on 2020-06-08 20:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20200608_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 20, 52, 17, 623952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 20, 52, 17, 622342, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 20, 52, 17, 623408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 20, 52, 17, 620404, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=256)),
                ('amount', models.FloatField(max_length=10)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 8, 20, 52, 17, 625218, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintxn', models.CharField(default='COMP123', max_length=256)),
                ('complain', models.CharField(max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 8, 20, 52, 17, 624540, tzinfo=utc))),
                ('complainid', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=0)),
                ('username', models.CharField(default='USER1', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
