# Generated by Django 3.0.2 on 2020-07-07 15:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200707_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('logo', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='selfpickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='airport',
            name='latitude',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitude',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='airport',
            name='state',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 15, 58, 57, 423796, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 15, 58, 57, 423109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 15, 58, 57, 419260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 15, 58, 57, 422498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 15, 58, 57, 424417, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 15, 58, 57, 420396, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightid', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('origin', models.CharField(max_length=256)),
                ('destination', models.CharField(max_length=256)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('seat', models.IntegerField(default=1, max_length=256)),
                ('Airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airline')),
            ],
        ),
        migrations.CreateModel(
            name='days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seat', models.IntegerField(default=1, max_length=256)),
                ('price', models.FloatField(max_length=256)),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routes')),
            ],
        ),
    ]
