# Generated by Django 3.0.2 on 2020-06-16 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200616_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='serves',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.cat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 13, 19, 3, 317750, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 13, 19, 3, 317178, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 13, 19, 3, 315451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 13, 19, 3, 316509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 13, 19, 3, 318341, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='services',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 13, 19, 3, 313260, tzinfo=utc)),
        ),
    ]
