# Generated by Django 3.0.2 on 2020-07-08 08:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200707_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='routeid',
            field=models.CharField(default='ROUTE1', max_length=256),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 8, 27, 16, 21076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 8, 27, 16, 20493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 8, 27, 16, 17249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 8, 27, 16, 19921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 8, 27, 16, 21677, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 8, 27, 16, 18055, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField(default=1, max_length=256)),
                ('pnr', models.CharField(max_length=256, unique=True)),
                ('amount', models.FloatField(max_length=256)),
                ('dayobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.days')),
            ],
        ),
    ]
