# Generated by Django 3.0.2 on 2020-07-17 10:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20200711_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=1, max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='total',
            field=models.IntegerField(default=0.0, max_length=256),
        ),
        migrations.AddField(
            model_name='tax',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AddField(
            model_name='tax',
            name='credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='rating',
            field=models.FloatField(default=1, max_length=256),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='total',
            field=models.IntegerField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 3, 3, 902453, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 3, 3, 901778, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 3, 3, 898466, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 3, 3, 901220, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 3, 3, 903095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 3, 3, 899388, tzinfo=utc)),
        ),
    ]
