# Generated by Django 3.0.2 on 2020-07-17 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200717_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 57, 32, 726082, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 57, 32, 725400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 57, 32, 722168, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.IntegerField(default=1, max_length=256),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 57, 32, 724853, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 57, 32, 726723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 10, 57, 32, 723053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='total',
            field=models.IntegerField(default=1, max_length=256),
        ),
    ]
