# Generated by Django 3.0.2 on 2020-07-22 08:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0016_auto_20200722_1410'),
        ('api', '0017_auto_20200717_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cab',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cab.cabOrder'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 8, 40, 54, 461143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 8, 40, 54, 460553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='selfpickup',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 8, 40, 54, 457124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 8, 40, 54, 459879, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 8, 40, 54, 461786, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 8, 40, 54, 458066, tzinfo=utc)),
        ),
    ]
