# Generated by Django 3.0.2 on 2020-07-23 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0018_auto_20200723_2240'),
        ('api', '0019_auto_20200722_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='cabIdle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='cabO',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cab.cabOrder'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 17, 10, 30, 99726, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 17, 10, 30, 99074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickupDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 17, 10, 30, 95631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 17, 10, 30, 95602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 17, 10, 30, 98519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 17, 10, 30, 100398, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 17, 10, 30, 96484, tzinfo=utc)),
        ),
    ]
