# Generated by Django 3.0.2 on 2020-07-28 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200728_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='accepted',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='rejected',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 9, 3, 595732, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 9, 3, 595123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickupDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 9, 3, 590452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 9, 3, 590424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productcomplain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 9, 3, 594484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 9, 3, 593608, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 9, 3, 596369, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 9, 3, 591325, tzinfo=utc)),
        ),
    ]
