# Generated by Django 3.0.2 on 2020-07-29 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200728_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 39, 44, 319823, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 39, 44, 319247, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickupDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 39, 44, 315241, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 39, 44, 315214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productcomplain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 39, 44, 318663, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='storerestro',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 39, 44, 318113, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 39, 44, 320598, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 39, 44, 316093, tzinfo=utc)),
        ),
    ]
