# Generated by Django 3.0.2 on 2020-07-29 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.CharField(max_length=50)),
                ('ITEM_ID', models.CharField(max_length=50)),
                ('EVENT_TYPE', models.CharField(max_length=50)),
                ('EVENT_VALUE', models.CharField(max_length=50)),
                ('TIMESTAMP', models.DateTimeField(default=datetime.datetime(2020, 7, 29, 8, 59, 25, 426481, tzinfo=utc))),
            ],
        ),
    ]
