# Generated by Django 3.0.2 on 2020-07-11 06:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cabdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=50)),
                ('carRegistration', models.CharField(max_length=50, unique=True)),
                ('carColor', models.CharField(max_length=10, unique=True)),
                ('rating', models.FloatField(default=1, max_length=4)),
                ('totalRides', models.IntegerField(default=0, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cabOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('seat', models.IntegerField(default=1, max_length=1)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 7, 11, 6, 26, 30, 862382, tzinfo=utc))),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab.cabdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
