# Generated by Django 3.0.2 on 2020-07-11 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartype', models.CharField(max_length=50, unique=True)),
                ('seat', models.IntegerField(default=1, max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 6, 34, 22, 399915, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='cabdetails',
            name='cartype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cab.carClass'),
            preserve_default=False,
        ),
    ]
