# Generated by Django 3.0.2 on 2020-07-11 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0002_auto_20200711_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caborder',
            name='cab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cab.cabdetails'),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 6, 43, 35, 810767, tzinfo=utc)),
        ),
    ]
