# Generated by Django 3.0.2 on 2020-07-11 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0004_auto_20200711_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caborder',
            old_name='latitude',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='caborder',
            old_name='longitude',
            new_name='latitudeDestination',
        ),
        migrations.AddField(
            model_name='caborder',
            name='latitudeOrigin',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caborder',
            name='longitudeDestination',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caborder',
            name='longitudeOrigin',
            field=models.CharField(default='22', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caborder',
            name='origin',
            field=models.CharField(default=54545, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 7, 27, 51, 600260, tzinfo=utc)),
        ),
    ]
