# Generated by Django 3.0.2 on 2020-07-11 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0005_auto_20200711_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='caborder',
            name='cabid',
            field=models.CharField(default='ccsc', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 7, 44, 41, 726300, tzinfo=utc)),
        ),
    ]
