# Generated by Django 3.0.2 on 2020-07-11 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0006_auto_20200711_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='caborder',
            name='accept',
            field=models.IntegerField(default=-1, max_length=1),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 8, 31, 47, 368083, tzinfo=utc)),
        ),
    ]
