# Generated by Django 3.0.2 on 2020-07-11 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0007_auto_20200711_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='caborder',
            name='cartype',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cab.carClass'),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 11, 11, 35, 39, 18735, tzinfo=utc)),
        ),
    ]
