# Generated by Django 3.0.2 on 2020-07-16 04:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0008_auto_20200711_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caborder',
            name='accept',
            field=models.IntegerField(default=-1, max_length=256),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='cabid',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='destination',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='latitudeDestination',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='latitudeOrigin',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='longitudeDestination',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='longitudeOrigin',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='origin',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='price',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='seat',
            field=models.IntegerField(default=1, max_length=256),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 4, 52, 50, 961272, tzinfo=utc)),
        ),
    ]
