# Generated by Django 3.0.2 on 2020-07-17 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0014_auto_20200717_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabdetails',
            name='carColor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 7, 23, 564544, tzinfo=utc)),
        ),
    ]
