# Generated by Django 3.0.2 on 2020-07-22 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0015_auto_20200717_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='caborder',
            name='pickupTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 8, 40, 54, 438316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 8, 40, 54, 438286, tzinfo=utc)),
        ),
    ]
