# Generated by Django 3.0.2 on 2020-07-22 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0016_auto_20200722_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caborder',
            name='pickupTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 8, 54, 6, 157188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 8, 54, 6, 157158, tzinfo=utc)),
        ),
    ]
