# Generated by Django 3.0.2 on 2020-07-23 17:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0017_auto_20200722_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caborder',
            name='pickupTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 17, 10, 30, 74993, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 17, 10, 30, 74940, tzinfo=utc)),
        ),
    ]
