# Generated by Django 3.0.2 on 2020-07-26 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0018_auto_20200723_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caborder',
            name='pickupTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 14, 52, 59, 831025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 14, 52, 59, 830990, tzinfo=utc)),
        ),
    ]
