# Generated by Django 3.0.2 on 2020-07-27 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0019_auto_20200726_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabdetails',
            name='accepted',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='cabdetails',
            name='rejected',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='pickupTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 54, 58, 108940, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 54, 58, 108905, tzinfo=utc)),
        ),
    ]
