# Generated by Django 3.0.2 on 2020-07-31 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0020_auto_20200728_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='caborder',
            name='From',
            field=models.BooleanField(default=True, max_length=256),
        ),
        migrations.AddField(
            model_name='caborder',
            name='airport',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='pickupTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 29, 40, 223033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 29, 40, 222996, tzinfo=utc)),
        ),
    ]
