# Generated by Django 3.0.2 on 2020-08-01 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0022_auto_20200802_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caborder',
            name='pickupTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 20, 7, 59, 322963, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='caborder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 20, 7, 59, 322932, tzinfo=utc)),
        ),
    ]
